env:
- PROJECT_NAME=real_estate PACKAGE_NAME=main
language: cpp
dist: bionic
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install qtbase5-dev qt5-default qttools5-dev libdbus-1-3 libxkbcommon-x11-0 xvfb gcc-7 g++-7 wget doxygen graphviz libgtest-dev -y
- cd /usr/src/gtest/ && sudo env "PATH=$PATH" cmake . && sudo env "PATH=$PATH" make
- sudo cp libgtest.a libgtest_main.a /usr/lib && cd -
- sudo apt-get install libopenblas-dev -y
- sudo apt-get install libdlib-dev -y
script:
- mkdir -p build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T $PROJECT_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uboristestov:$BINTRAY_API_KEY "https://api.bintray.com/content/boristestov/$PROJECT_NAME/$PACKAGE_NAME/$TRAVIS_BUILD_NUMBER/$PROJECT_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
